#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Truthful Machine-Readable Scope Matrix Generator for DR0-DR42.

Constructs customer_demo/CUSTOMER_SCOPE.json according to Phase A of the
Customer-Critical Review and Offline NPU-Only Acceptance Directive.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CUSTOMER_DEMO_DIR = REPO_ROOT / "customer_demo"


def generate_scope_matrix() -> dict[str, object]:
    drs: list[dict[str, object]] = [
        {
            "dr_id": "DR0",
            "claimed_operation": "M33 Ring Product Vector Unit (256-coeff polynomial multiplication in Z_q[X]/(X^256+1))",
            "customer_demo_relevance": "FOUNDATION_COMPONENT",
            "dependencies": [],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/m33_product.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/m33_product_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/m33_product_abi.py"
            },
            "compiled_artifact": "build/m33_product.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2); 2 inbound ObjectFifos; 32-byte alignment",
            "secret_inputs": "None (algebraic kernel)",
            "public_inputs": "Polynomial vectors a, b in Z_q[X]/(X^256+1)",
            "final_outputs": "Polynomial vector c = a * b (512 bytes)",
            "normative_source": "Ring-LWE / Module-LWE polynomial arithmetic foundations",
            "vector_set": "Repository verified ring product test vectors",
            "independent_oracle": "Host Python polynomial ring reference oracle",
            "host_involvement": "Input coefficient packing, zero-copy buffer dispatch, output unpack",
            "device_resident_computation": "NTT/Montgomery coefficient-wise ring multiplication on AIE2 vector ALU",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 24,
            "registered_canonical_test_count": 24,
            "latest_observed_functional_result": "24/24 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR1",
            "claimed_operation": "ML-DSA-44 RejNTT Matrix Expansion (SampleInBall / RejNTTPoly)",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR0"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr1_mldsa44_rejntt.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr1_mldsa44_rejntt_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr1_mldsa44_rejntt_abi.py"
            },
            "compiled_artifact": "build/dr1_mldsa44_rejntt.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2); SHAKE128 output stream, RejNTT sampler",
            "secret_inputs": "None (public matrix expansion)",
            "public_inputs": "Seed rho (32 bytes), matrix index (r, c)",
            "final_outputs": "NTT polynomial coefficients in Z_q (256 * 4 bytes)",
            "normative_source": "NIST FIPS 204 Section 7.1 (Algorithm 29/30: RejNTTPoly)",
            "vector_set": "NIST ACVP ML-DSA-44 KAT vectors",
            "independent_oracle": "Independent FIPS 204 host reference",
            "host_involvement": "Seed marshaling, DMA buffer dispatch, output comparison",
            "device_resident_computation": "SHAKE128 stream absorption and rejection sampling directly on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 33,
            "registered_canonical_test_count": 33,
            "latest_observed_functional_result": "33/33 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR2a",
            "claimed_operation": "ML-KEM-512 SampleNTT (Algorithm 6 Parse)",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR0"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr2a_mlkem512_samplentt.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr2a_mlkem512_samplentt_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr2a_mlkem512_samplentt_abi.py"
            },
            "compiled_artifact": "build/dr2a_mlkem512_samplentt.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2); 32-byte aligned stream",
            "secret_inputs": "None (public matrix parse)",
            "public_inputs": "XOF byte stream (384 bytes per polynomial)",
            "final_outputs": "256 NTT coefficients in Z_q",
            "normative_source": "NIST FIPS 203 Section 4.2.1 (Algorithm 6 SampleNTT)",
            "vector_set": "Derived from official NIST ACVP ML-KEM-512 vectors",
            "independent_oracle": "Independent FIPS 203 host reference",
            "host_involvement": "Buffer marshaling, zero-copy dispatch, comparison",
            "device_resident_computation": "Rejection sampling and canonical range reduction on tile ALU",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 13,
            "registered_canonical_test_count": 13,
            "latest_observed_functional_result": "13/13 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR2b",
            "claimed_operation": "ML-KEM-512 Centered Binomial Distribution CBD_eta + Forward NTT",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR0", "DR2a"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr2b_mlkem512_noise_ntt.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr2b_mlkem512_noise_ntt_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr2b_mlkem512_noise_ntt_abi.py"
            },
            "compiled_artifact": "build/dr2b_mlkem512_noise_ntt.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2); 2 inbound streams",
            "secret_inputs": "Noise seed / PRF output stream",
            "public_inputs": "None",
            "final_outputs": "Polynomial in NTT domain (512 bytes)",
            "normative_source": "NIST FIPS 203 Section 4.2.2 (CBD_3) and Section 4.2.3 (NTT)",
            "vector_set": "Derived from official NIST ACVP ML-KEM-512 vectors",
            "independent_oracle": "Independent FIPS 203 host reference",
            "host_involvement": "Buffer marshaling, dispatch, comparison",
            "device_resident_computation": "CBD bit parsing, subtraction, and Cooley-Tukey Radix-2 NTT on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 13,
            "registered_canonical_test_count": 13,
            "latest_observed_functional_result": "13/13 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR2c",
            "claimed_operation": "ML-KEM-512 KeyGen Row Multiplier (Vector NTT multiply-accumulate A[row] * s + e)",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR0", "DR2b"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr2c_mlkem512_keygen_row.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr2c_mlkem512_keygen_row_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr2c_mlkem512_keygen_row_abi.py"
            },
            "compiled_artifact": "build/dr2c_mlkem512_keygen_row.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2); 2 inbound ObjectFifos",
            "secret_inputs": "Secret vector s (k=2 polynomials in NTT domain)",
            "public_inputs": "Public matrix row A (k=2 polynomials), error e",
            "final_outputs": "Public key row polynomial t[row] = A[row]*s + e",
            "normative_source": "NIST FIPS 203 Section 5.1 (Algorithm 12: K-PKE.KeyGen steps)",
            "vector_set": "Derived from official NIST ACVP ML-KEM-512 vectors",
            "independent_oracle": "Independent FIPS 203 host reference",
            "host_involvement": "Buffer marshaling, dispatch, comparison",
            "device_resident_computation": "Montgomery pointwise multiply and Montgomery accumulation on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 11,
            "registered_canonical_test_count": 11,
            "latest_observed_functional_result": "11/11 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR2d",
            "claimed_operation": "ML-KEM-512 K-PKE KeyGen (Complete Pipeline: matrix expansion, secret noise, public key generation)",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR0", "DR2a", "DR2b", "DR2c"],
            "source_files": [
                "phoenix_sdr_dsp/pqc/kernels/dr2d_kpke_keygen.cc",
                "phoenix_sdr_dsp/pqc/kernels/dr2d_kpke_keygen_internal.hpp"
            ],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr2d_mlkem512_kpke_keygen_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr2d_mlkem512_kpke_keygen_abi.py"
            },
            "compiled_artifact": "build/dr2d_mlkem512_kpke_keygen.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3); 2 ObjectFifos; 32-byte alignment",
            "secret_inputs": "Seed d (32 bytes)",
            "public_inputs": "None",
            "final_outputs": "Public key ek_pke (800 bytes), private key dk_pke (768 bytes)",
            "normative_source": "NIST FIPS 203 Section 5.1 (Algorithm 12 K-PKE.KeyGen)",
            "vector_set": "Official NIST ACVP ML-KEM-512 KAT vectors (25 cases)",
            "independent_oracle": "Independent FIPS 203 host reference oracle",
            "host_involvement": "Input seed marshaling, zero-copy buffer dispatch, status verification, 100% full buffer comparison",
            "device_resident_computation": "G(d) expansion, SampleNTT for A, CBD_3 for s and e, NTT, Montgomery mult, byte packing on device",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 25,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR3",
            "claimed_operation": "ML-KEM-512 K-PKE Encrypt",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR2d"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr3_kpke_encrypt.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr3_mlkem512_kpke_encrypt_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr3_mlkem512_kpke_encrypt_abi.py"
            },
            "compiled_artifact": "build/dr3_mlkem512_kpke_encrypt.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "Ephemeral randomness m (32 bytes)",
            "public_inputs": "Public key ek_pke (800 bytes)",
            "final_outputs": "Ciphertext c (768 bytes)",
            "normative_source": "NIST FIPS 203 Section 5.2 (Algorithm 13 K-PKE.Encrypt)",
            "vector_set": "Official NIST ACVP ML-KEM-512 KAT vectors (25 cases)",
            "independent_oracle": "Independent FIPS 203 host reference oracle",
            "host_involvement": "Input marshaling, zero-copy buffer dispatch, comparison",
            "device_resident_computation": "Matrix-vector multiply A^T * r, error addition, message encoding, compression",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 25,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR4",
            "claimed_operation": "ML-KEM-512 K-PKE Decrypt",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR3"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr4_kpke_decrypt.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr4_mlkem512_kpke_decrypt_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr4_mlkem512_kpke_decrypt_abi.py"
            },
            "compiled_artifact": "build/dr4_mlkem512_kpke_decrypt.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "Decryption key dk_pke (768 bytes)",
            "public_inputs": "Ciphertext c (768 bytes)",
            "final_outputs": "Decrypted message m (32 bytes)",
            "normative_source": "NIST FIPS 203 Section 5.3 (Algorithm 14 K-PKE.Decrypt)",
            "vector_set": "Official NIST ACVP ML-KEM-512 KAT vectors (25 cases)",
            "independent_oracle": "Independent FIPS 203 host reference oracle",
            "host_involvement": "Input marshaling, zero-copy dispatch, comparison",
            "device_resident_computation": "Decompression, INTT, inner product s^T * u, decompression and rounding to 32 bytes",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 25,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR5",
            "claimed_operation": "ML-KEM-512 Complete ML-KEM.KeyGen",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR2d"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr5_mlkem_keygen.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr5_mlkem512_keygen_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr5_mlkem512_keygen_abi.py"
            },
            "compiled_artifact": "build/dr5_mlkem512_keygen.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "Seeds d (32 bytes), z (32 bytes)",
            "public_inputs": "None",
            "final_outputs": "Encapsulation key ek (800 bytes), decapsulation key dk (1632 bytes)",
            "normative_source": "NIST FIPS 203 Section 6.1 (Algorithm 15 ML-KEM.KeyGen)",
            "vector_set": "Official NIST ACVP ML-KEM-512 KAT vectors (25 cases)",
            "independent_oracle": "Independent FIPS 203 host reference oracle",
            "host_involvement": "Seed input marshaling, zero-copy buffer dispatch, full buffer comparison",
            "device_resident_computation": "K-PKE.KeyGen, H(ek) digest computation, dk concatenation (dk_pke || ek || H(ek) || z)",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 25,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR6",
            "claimed_operation": "ML-KEM-512 Complete ML-KEM.Encaps",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR3", "DR5"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr6_mlkem_encaps.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr6_mlkem512_encaps_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr6_mlkem512_encaps_abi.py"
            },
            "compiled_artifact": "build/dr6_mlkem512_encaps.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "Randomness m (32 bytes)",
            "public_inputs": "Encapsulation key ek (800 bytes)",
            "final_outputs": "Shared secret K (32 bytes), ciphertext c (768 bytes)",
            "normative_source": "NIST FIPS 203 Section 6.2 (Algorithm 16 ML-KEM.Encaps)",
            "vector_set": "Official NIST ACVP ML-KEM-512 KAT vectors (25 cases)",
            "independent_oracle": "Independent FIPS 203 host reference oracle",
            "host_involvement": "Input marshaling, zero-copy buffer dispatch, comparison",
            "device_resident_computation": "(K, r) = G(m || H(ek)), K-PKE.Encrypt(ek, m, r)",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 25,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR7",
            "claimed_operation": "ML-KEM-512 Complete ML-KEM.Decaps (Fujisaki-Okamoto Transform with Implicit Rejection)",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR4", "DR6"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr7_mlkem_decaps.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr7_mlkem512_decaps_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr7_mlkem512_decaps_abi.py"
            },
            "compiled_artifact": "build/dr7_mlkem512_decaps.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "Decapsulation key dk (1632 bytes)",
            "public_inputs": "Ciphertext c (768 bytes)",
            "final_outputs": "Shared secret K (32 bytes)",
            "normative_source": "NIST FIPS 203 Section 6.3 (Algorithm 17 ML-KEM.Decaps)",
            "vector_set": "Official NIST ACVP ML-KEM-512 KAT vectors (25 cases, including invalid ciphertexts)",
            "independent_oracle": "Independent FIPS 203 host reference oracle",
            "host_involvement": "Input marshaling, zero-copy dispatch, comparison",
            "device_resident_computation": "K-PKE.Decrypt, re-encrypt, constant-time ciphertext comparison, constant-time select between K_valid and K_rejection",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 25,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR8",
            "claimed_operation": "ML-KEM-768 and ML-KEM-1024 Parameter-Set Expansion (KeyGen, Encaps, Decaps)",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR5", "DR6", "DR7"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr8_mlkem_unified.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr8_mlkem_unified_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr8_mlkem_unified_abi.py"
            },
            "compiled_artifact": "build/dr8_mlkem_unified.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3); multi-tile parameter dispatch",
            "secret_inputs": "Seeds / private keys for ML-KEM-768 and ML-KEM-1024",
            "public_inputs": "Public keys / ciphertexts",
            "final_outputs": "Keys, ciphertexts, shared secrets for 768 and 1024",
            "normative_source": "NIST FIPS 203 Section 8 (Parameter Sets ML-KEM-768, ML-KEM-1024)",
            "vector_set": "Official NIST ACVP ML-KEM-768 and ML-KEM-1024 KAT vectors (75 cases)",
            "independent_oracle": "Independent FIPS 203 host reference oracle",
            "host_involvement": "Input marshaling, zero-copy dispatch, comparison",
            "device_resident_computation": "Parameterized k=3 and k=4 matrix operations, CBD_2, NTT, compression",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 75,
            "registered_canonical_test_count": 75,
            "latest_observed_functional_result": "75/75 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR9",
            "claimed_operation": "Reusable FIPS 202 SHA-3 & SHAKE Service (SHA3-224, 256, 384, 512, SHAKE128, SHAKE256)",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": [],
            "source_files": [
                "phoenix_sdr_dsp/pqc/kernels/dr9_fips202.cc",
                "phoenix_sdr_dsp/pqc/kernels/dr9_keccak1600.hpp"
            ],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr9_fips202_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr9_fips202_abi.py"
            },
            "compiled_artifact": "build/dr9_fips202.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2); 64-bit vector Keccak lane mapping",
            "secret_inputs": "None (cryptographic hash function)",
            "public_inputs": "Arbitrary byte message (up to 4096 bytes)",
            "final_outputs": "Digest or squeezed output (up to 512 bytes)",
            "normative_source": "NIST FIPS 202 (Keccak-p[1600, 24] Permutation, SHA-3, SHAKE)",
            "vector_set": "Official NIST CAVP FIPS 202 Byte-KAT vectors (122 cases)",
            "independent_oracle": "Independent FIPS 202 host reference oracle",
            "host_involvement": "Input marshaling, zero-copy dispatch, comparison",
            "device_resident_computation": "Theta, Rho, Pi, Chi, Iota rounds directly on tile ALU",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 122,
            "registered_canonical_test_count": 122,
            "latest_observed_functional_result": "122/122 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR10",
            "claimed_operation": "Sealed Lifecycle Architecture & Hardware Key Sources",
            "customer_demo_relevance": "FOUNDATION_COMPONENT",
            "dependencies": ["DR5", "DR9"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr10_sealed_lifecycle.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr10_sealed_lifecycle_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr10_sealed_lifecycle_abi.py"
            },
            "compiled_artifact": "build/dr10_sealed_lifecycle.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "Master key material and lifecycle state tokens",
            "public_inputs": "Transition command descriptors",
            "final_outputs": "Status records and sealed key descriptors (40 cases)",
            "normative_source": "Repository Security Model & Sealed Architecture Specifications",
            "vector_set": "Repository protocol transition vectors",
            "independent_oracle": "Host security state machine oracle",
            "host_involvement": "Command dispatch, status monitoring, verification",
            "device_resident_computation": "State transitions, key derivation, zeroization on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 40,
            "registered_canonical_test_count": 40,
            "latest_observed_functional_result": "40/40 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR11",
            "claimed_operation": "FIPS 204 ML-DSA-44 KeyGen",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR1", "DR9"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr11_mldsa44_keygen.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr11_mldsa44_keygen_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr11_mldsa44_keygen_abi.py"
            },
            "compiled_artifact": "build/dr11_mldsa44_keygen.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "Seed xi (32 bytes)",
            "public_inputs": "None",
            "final_outputs": "Public key pk (1312 bytes), secret key sk (2560 bytes)",
            "normative_source": "NIST FIPS 204 Section 5.1 (Algorithm 1 ML-DSA.KeyGen)",
            "vector_set": "Official NIST ACVP ML-DSA-44 KAT vectors (25 cases)",
            "independent_oracle": "Independent FIPS 204 host reference oracle",
            "host_involvement": "Seed marshaling, zero-copy buffer dispatch, full buffer comparison",
            "device_resident_computation": "SHAKE256 expansion, RejBoundedPoly for s1/s2, NTT, matrix mult A*s1, Power2Round, bit packing",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 25,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR12",
            "claimed_operation": "FIPS 204 ML-DSA-44 Sign",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR11"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr12_mldsa44_sign.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr12_mldsa44_sign_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr12_mldsa44_sign_abi.py"
            },
            "compiled_artifact": "build/dr12_mldsa44_sign.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "Secret key sk (2560 bytes)",
            "public_inputs": "Message M, optional deterministic seed rnd",
            "final_outputs": "Signature sigma (2420 bytes)",
            "normative_source": "NIST FIPS 204 Section 5.2 (Algorithm 2 ML-DSA.Sign)",
            "vector_set": "Official NIST ACVP ML-DSA-44 KAT vectors (30 cases)",
            "independent_oracle": "Independent FIPS 204 host reference oracle",
            "host_involvement": "Input marshaling, zero-copy dispatch, full buffer comparison",
            "device_resident_computation": "Mask vector sampling, matrix-vector product, rejection checks (norm bounds), challenge polynomial, hint generation",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 30,
            "registered_canonical_test_count": 30,
            "latest_observed_functional_result": "30/30 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR13",
            "claimed_operation": "FIPS 204 ML-DSA-44 Verify",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR12"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr13_mldsa44_verify.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr13_mldsa44_verify_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr13_mldsa44_verify_abi.py"
            },
            "compiled_artifact": "build/dr13_mldsa44_verify.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "None (public verification)",
            "public_inputs": "Public key pk (1312 bytes), message M, signature sigma (2420 bytes)",
            "final_outputs": "Verification boolean result (1 byte: 1=VALID, 0=REJECT)",
            "normative_source": "NIST FIPS 204 Section 5.3 (Algorithm 3 ML-DSA.Verify)",
            "vector_set": "Official NIST ACVP ML-DSA-44 KAT vectors (30 cases, valid and tampered)",
            "independent_oracle": "Independent FIPS 204 host reference oracle",
            "host_involvement": "Input marshaling, zero-copy dispatch, status comparison",
            "device_resident_computation": "Matrix expansion, z norm check, w1 reconstruction, c hash verification",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 30,
            "registered_canonical_test_count": 30,
            "latest_observed_functional_result": "30/30 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR14",
            "claimed_operation": "FIPS 204 ML-DSA-65 Complete Suite (KeyGen, Sign, Verify)",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR13"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr14_mldsa65.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr14_mldsa65_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr14_mldsa65_abi.py"
            },
            "compiled_artifact": "build/dr14_mldsa65.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3); (k=6, l=5) matrix dimensioning",
            "secret_inputs": "Seeds / secret keys for ML-DSA-65",
            "public_inputs": "Public keys, messages, signatures",
            "final_outputs": "Keys (pk: 1952 bytes, sk: 4032 bytes), signatures (3309 bytes), verification booleans",
            "normative_source": "NIST FIPS 204 Section 8 (Parameter Set ML-DSA-65)",
            "vector_set": "Official NIST ACVP ML-DSA-65 KAT vectors (85 cases)",
            "independent_oracle": "Independent FIPS 204 host reference oracle",
            "host_involvement": "Input marshaling, zero-copy buffer dispatch, comparison",
            "device_resident_computation": "Matrix operations, rejection sampling, signature generation and verification on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 85,
            "registered_canonical_test_count": 85,
            "latest_observed_functional_result": "85/85 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR15",
            "claimed_operation": "FIPS 204 ML-DSA-87 Complete Suite (KeyGen, Sign, Verify)",
            "customer_demo_relevance": "CORE_DEMO_PRIMITIVE",
            "dependencies": ["DR14"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr15_mldsa87.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr15_mldsa87_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr15_mldsa87_abi.py"
            },
            "compiled_artifact": "build/dr15_mldsa87.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3); (k=8, l=7) matrix dimensioning",
            "secret_inputs": "Seeds / secret keys for ML-DSA-87",
            "public_inputs": "Public keys, messages, signatures",
            "final_outputs": "Keys (pk: 2592 bytes, sk: 4896 bytes), signatures (4627 bytes), verification booleans",
            "normative_source": "NIST FIPS 204 Section 8 (Parameter Set ML-DSA-87)",
            "vector_set": "Official NIST ACVP ML-DSA-87 KAT vectors (85 cases)",
            "independent_oracle": "Independent FIPS 204 host reference oracle",
            "host_involvement": "Input marshaling, zero-copy buffer dispatch, comparison",
            "device_resident_computation": "Matrix operations, rejection sampling, signature generation and verification on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 85,
            "registered_canonical_test_count": 85,
            "latest_observed_functional_result": "85/85 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR16",
            "claimed_operation": "ETSI GS QKD 014 Sealed Ingress",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR9", "DR10"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr16_etsi_qkd014.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr16_etsi_qkd014_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr16_etsi_qkd014_abi.py"
            },
            "compiled_artifact": "build/dr16_etsi_qkd014.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "External QKD key material (ingressed from host buffer)",
            "public_inputs": "Key ID tokens and metadata",
            "final_outputs": "Internal sealed key container descriptors (25 cases)",
            "normative_source": "ETSI GS QKD 014 REST-based key delivery API",
            "vector_set": "Repository protocol vectors",
            "independent_oracle": "Host ETSI reference",
            "host_involvement": "Key transport, buffer dispatch, comparison",
            "device_resident_computation": "Key format parsing, integrity checks, sealed storage directly on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 25,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR17",
            "claimed_operation": "ML-DSA Asymmetric QKD Control",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR13", "DR16"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr17_mldsa_qkd_auth.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr17_mldsa_qkd_auth_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr17_mldsa_qkd_auth_abi.py"
            },
            "compiled_artifact": "build/dr17_mldsa_qkd_auth.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "None",
            "public_inputs": "QKD control commands and ML-DSA signatures",
            "final_outputs": "Authorized command execution status (25 cases)",
            "normative_source": "ETSI GS QKD 014 / NIST FIPS 204",
            "vector_set": "Derived from official NIST ACVP vectors",
            "independent_oracle": "Host authentication oracle",
            "host_involvement": "Command marshaling, buffer dispatch, comparison",
            "device_resident_computation": "ML-DSA verification before releasing QKD session actions on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 25,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR18",
            "claimed_operation": "NIST SP 800-56C Dual Combiner",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR7", "DR9", "DR16"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr18_dual_key_combiner.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr18_dual_key_combiner_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr18_dual_key_combiner_abi.py"
            },
            "compiled_artifact": "build/dr18_dual_key_combiner.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "QKD shared key Z_qkd, PQC shared key Z_pqc",
            "public_inputs": "Context string, label",
            "final_outputs": "Combined master key K_master (32 bytes)",
            "normative_source": "NIST SP 800-56C Rev 2 (Two-Step Key Derivation / Feedback KDF)",
            "vector_set": "Derived from NIST SP 800-56C test vectors (25 cases)",
            "independent_oracle": "Independent SP 800-56C host reference oracle",
            "host_involvement": "Key marshaling, zero-copy buffer dispatch, comparison",
            "device_resident_computation": "KMAC/HKDF extraction and expansion over dual secret inputs directly on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 25,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR19",
            "claimed_operation": "Hybrid QKD-PQC Session Orchestrator",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR16", "DR17", "DR18"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr19_hybrid_session.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr19_hybrid_session_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr19_hybrid_session_abi.py"
            },
            "compiled_artifact": "build/dr19_hybrid_session.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "Session keys and state tokens",
            "public_inputs": "Session negotiation packets",
            "final_outputs": "Session control records and encrypted channel descriptors (25 cases)",
            "normative_source": "Hybrid QKD-PQC Protocol Design Specification",
            "vector_set": "Repository protocol vectors",
            "independent_oracle": "Host session reference",
            "host_involvement": "Packet marshaling, buffer dispatch, comparison",
            "device_resident_computation": "Session key lifecycle, ratchet transitions on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 25,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR20",
            "claimed_operation": "Undefined / Reserved Scope",
            "customer_demo_relevance": "BLOCKED",
            "dependencies": [],
            "source_files": [],
            "graph_and_abi": {"graph": None, "abi": None},
            "compiled_artifact": None,
            "tile_assignment_and_topology": None,
            "secret_inputs": None,
            "public_inputs": None,
            "final_outputs": None,
            "normative_source": "None supplied (Identifier unallocated)",
            "vector_set": "None",
            "independent_oracle": "None",
            "host_involvement": None,
            "device_resident_computation": None,
            "potential_fallback_paths": "NONE",
            "expected_test_count": 0,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "SPECIFICATION_BLOCKED",
            "physical_provenance_status": "PHYSICAL_VERIFICATION_BLOCKED",
            "known_semantic_security_status": "BLOCKED",
            "blocker": "DR20-SCOPE (No authoritative DR20 scope supplied)",
            "final_classification": "DEPENDENCY_BLOCKED"
        },
        {
            "dr_id": "DR21",
            "claimed_operation": "NIST FIPS 205 SLH-DSA (KeyGen, Sign, Verify)",
            "customer_demo_relevance": "QUARANTINED",
            "dependencies": ["DR9"],
            "source_files": [
                "phoenix_sdr_dsp/pqc/kernels/dr21_slhdsa_service.cc",
                "phoenix_sdr_dsp/pqc/kernels/dr21_slhdsa_internal.hpp"
            ],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr21_slhdsa_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr21_slhdsa_abi.py"
            },
            "compiled_artifact": "build/dr21_slhdsa.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "SLH-DSA private key material",
            "public_inputs": "Public keys, messages, signatures",
            "final_outputs": "Signatures, verification booleans",
            "normative_source": "NIST FIPS 205 (SLH-DSA / SPHINCS+)",
            "vector_set": "Repository test cases (25 cases)",
            "independent_oracle": "DR21 internal host reference (reproduces shortcut)",
            "host_involvement": "Input marshaling, buffer dispatch, comparison",
            "device_resident_computation": "DEFECTIVE: Hypertree verify accepts unauthenticated SHAKE hash tail over public keys and arbitrary FORS bytes",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "QUARANTINED (Public Forgery Reproducible)",
            "physical_provenance_status": "QUARANTINED",
            "known_semantic_security_status": "CRITICAL_SEMANTIC_DEFECT",
            "blocker": "DR21-HYPERTREE-FORGERY (Verification shortcut allows public-only forgeries)",
            "final_classification": "BLOCKED_THREE_STRIKES"
        },
        {
            "dr_id": "DR22",
            "claimed_operation": "NIST FIPS 206 FN-DSA (KeyGen, Sign, Verify)",
            "customer_demo_relevance": "QUARANTINED",
            "dependencies": ["DR9"],
            "source_files": [
                "phoenix_sdr_dsp/pqc/kernels/dr22_fndsa_service.cc",
                "phoenix_sdr_dsp/pqc/kernels/dr22_fndsa_internal.hpp"
            ],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr22_fndsa_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr22_fndsa_abi.py"
            },
            "compiled_artifact": "build/dr22_fndsa.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "Private key (IGNORED BY SIGNING KERNEL)",
            "public_inputs": "Salt, public key, message",
            "final_outputs": "Signature, verification boolean",
            "normative_source": "Draft NIST FIPS 206 (FN-DSA / Falcon)",
            "vector_set": "Repository test cases (25 cases)",
            "independent_oracle": "DR22 internal host reference",
            "host_involvement": "Input marshaling, buffer dispatch, comparison",
            "device_resident_computation": "DEFECTIVE: Signing constructs s2 from public values only without reading secret key; fixed 512-element buffers overflow on n=1024",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "QUARANTINED (Secret-Free Signing & Stack Overflow)",
            "physical_provenance_status": "QUARANTINED",
            "known_semantic_security_status": "CRITICAL_SEMANTIC_DEFECT",
            "blocker": "DR22-SECRET-FREE-SIGNING (Public signature generation and 1024 array overflow)",
            "final_classification": "BLOCKED_THREE_STRIKES"
        },
        {
            "dr_id": "DR23",
            "claimed_operation": "OpenSSL 3.x Provider & OASIS PKCS#11 HSM Host Layer",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR5", "DR6", "DR7", "DR11", "DR12", "DR13"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr23_openssl_pkcs11.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr23_openssl_pkcs11_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr23_openssl_pkcs11_abi.py"
            },
            "compiled_artifact": "build/dr23_openssl_pkcs11.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "HSM token credentials and PINs",
            "public_inputs": "PKCS#11 function invocation structures",
            "final_outputs": "Cryptoki return values and exported public artifacts (25 cases)",
            "normative_source": "OASIS PKCS#11 v3.0 / OpenSSL 3.0 Provider API",
            "vector_set": "Repository test vectors",
            "independent_oracle": "Host Cryptoki state machine oracle",
            "host_involvement": "Provider dispatch, buffer transport, comparison",
            "device_resident_computation": "Hardware token session management and cryptographic dispatch on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "CANONICAL-RUNNER-UNREGISTERED",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR24",
            "claimed_operation": "RFC 9370 Multi-KEM IPsec & WireGuard Acceleration",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR7", "DR18"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr24_ipsec_wireguard.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr24_ipsec_wireguard_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr24_ipsec_wireguard_abi.py"
            },
            "compiled_artifact": "build/dr24_ipsec_wireguard.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "Pre-shared keys and decapsulation keys",
            "public_inputs": "IKEv2 / WireGuard handshake payloads",
            "final_outputs": "Derived tunnel keys and key exchange payloads (25 cases)",
            "normative_source": "RFC 9370 (Multiple Key Exchanges in IKEv2)",
            "vector_set": "Repository test vectors",
            "independent_oracle": "Host IKEv2 reference oracle",
            "host_involvement": "Packet marshaling, buffer dispatch, comparison",
            "device_resident_computation": "Multi-KEM combiner and tunnel key expansion on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "CANONICAL-RUNNER-UNREGISTERED",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR25",
            "claimed_operation": "Higher-Order Polynomial Masking & Local PRNG Expansion",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR0", "DR9"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr25_masking_prng.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr25_masking_prng_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr25_masking_prng_abi.py"
            },
            "compiled_artifact": "build/dr25_masking_prng.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "Secret unmasked polynomial",
            "public_inputs": "Masking randomness seed",
            "final_outputs": "Masked polynomial shares (25 cases)",
            "normative_source": "Side-Channel Masking Foundations for Lattice-Based Cryptography",
            "vector_set": "Repository masking test vectors",
            "independent_oracle": "Host masking reference oracle",
            "host_involvement": "Buffer marshaling, dispatch, comparison",
            "device_resident_computation": "Order-d additive share generation and arithmetic-to-Boolean conversion on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "CANONICAL-RUNNER-UNREGISTERED",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR26",
            "claimed_operation": "AMD XDNA 2 & Alveo V70 Multi-Architecture Scaling",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR0"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr26_multi_arch.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr26_multi_arch_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr26_multi_arch_abi.py"
            },
            "compiled_artifact": "build/dr26_multi_arch.xclbin",
            "tile_assignment_and_topology": "AIE2 / AIE2P Multi-device abstraction",
            "secret_inputs": "None",
            "public_inputs": "Target architecture descriptor",
            "final_outputs": "Compatibility and dispatch mapping structures (25 cases)",
            "normative_source": "AMD XDNA / AIE2 Architecture Reference Manuals",
            "vector_set": "Repository multi-arch test vectors",
            "independent_oracle": "Host target configuration oracle",
            "host_involvement": "Dispatch routing, comparison",
            "device_resident_computation": "Architecture feature probing and dynamic pipeline dispatch",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "CANONICAL-RUNNER-UNREGISTERED",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR27",
            "claimed_operation": "QRNG-OPENAPI & Entropy Reservoir",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR9"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr27_qrng_reservoir.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr27_qrng_reservoir_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr27_qrng_reservoir_abi.py"
            },
            "compiled_artifact": "build/dr27_qrng_reservoir.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "Raw entropy bytes from external quantum source",
            "public_inputs": "Entropy test commands",
            "final_outputs": "Conditioned entropy buffers and health test status (21 cases)",
            "normative_source": "NIST SP 800-90B / QRNG-OpenAPI Specification",
            "vector_set": "Repository entropy test vectors",
            "independent_oracle": "Host entropy evaluation oracle",
            "host_involvement": "Entropy streaming, buffer dispatch, comparison",
            "device_resident_computation": "NIST SP 800-90B continuous health tests (RCT, APT) and conditioning on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 21,
            "registered_canonical_test_count": 21,
            "latest_observed_functional_result": "21/21 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "PHYSICAL-DISPATCH-CORROBORATION",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR28",
            "claimed_operation": "NIST SP 800-208 / RFC 8554 LMS Stateless Verification Engine",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR9"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr28_lms_verifier.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr28_lms_verifier_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr28_lms_verifier_abi.py"
            },
            "compiled_artifact": "build/dr28_lms_verifier.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "None (stateless public key verification)",
            "public_inputs": "LMS public key, message, signature",
            "final_outputs": "Verification boolean (25 cases)",
            "normative_source": "RFC 8554 (Leighton-Micali Hash-Based Signatures) / NIST SP 800-208",
            "vector_set": "RFC 8554 Appendix F test vectors",
            "independent_oracle": "Host LMS reference oracle",
            "host_involvement": "Input marshaling, buffer dispatch, comparison",
            "device_resident_computation": "LM-OTS verification, Merkle authentication path evaluation directly on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "CANONICAL-RUNNER-UNREGISTERED",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR29",
            "claimed_operation": "NSA CNSA 2.0 Level 5 Multi-Tile Distributed Memory Engine",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR8", "DR15"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr29_cnsa_distributed.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr29_cnsa_distributed_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr29_cnsa_distributed_abi.py"
            },
            "compiled_artifact": "build/dr29_cnsa_distributed.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,5); 4-tile distributed memory array",
            "secret_inputs": "CNSA Level 5 key material",
            "public_inputs": "High-security workload payloads",
            "final_outputs": "Distributed transform outputs (25 cases)",
            "normative_source": "NSA Commercial National Security Algorithm Suite 2.0",
            "vector_set": "Repository CNSA test vectors",
            "independent_oracle": "Host CNSA reference oracle",
            "host_involvement": "Distributed buffer dispatch, comparison",
            "device_resident_computation": "Cross-tile parallel matrix operations and memory coordination",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "CANONICAL-RUNNER-UNREGISTERED",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR30",
            "claimed_operation": "3GPP TS 33.501 5G/6G SUCI Co-Processor",
            "customer_demo_relevance": "QUARANTINED",
            "dependencies": ["DR7"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr30_3gpp_suci.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr30_3gpp_suci_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr30_3gpp_suci_abi.py"
            },
            "compiled_artifact": "build/dr30_3gpp_suci.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "DEFECTIVE: Host provides precomputed shared secret",
            "public_inputs": "Encrypted SUCI identity descriptor",
            "final_outputs": "De-concealed SUPI identity",
            "normative_source": "3GPP TS 33.501 Section 6.12",
            "vector_set": "Repository SUCI test cases (25 cases)",
            "independent_oracle": "DR30 internal host oracle",
            "host_involvement": "DEFECTIVE: Host computes ML-KEM decapsulation and sends shared secret to NPU",
            "device_resident_computation": "KDF and XOR over host-supplied shared secret; NOT on-device ML-KEM decapsulation",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "QUARANTINED (Host Shared Secret Substitution)",
            "physical_provenance_status": "QUARANTINED",
            "known_semantic_security_status": "CRITICAL_SEMANTIC_DEFECT",
            "blocker": "DR30-HOST-SHARED-SECRET (Device receives precomputed shared secret from host)",
            "final_classification": "BLOCKED_THREE_STRIKES"
        },
        {
            "dr_id": "DR31",
            "claimed_operation": "X.509 Post-Quantum Certificates & Hybrid CMS Co-Processor",
            "customer_demo_relevance": "QUARANTINED",
            "dependencies": ["DR7", "DR13"],
            "source_files": [
                "phoenix_sdr_dsp/pqc/kernels/dr31_x509_cms.cc",
                "phoenix_sdr_dsp/pqc/kernels/dr31_x509_cms_internal.hpp"
            ],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr31_x509_cms_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr31_x509_cms_abi.py"
            },
            "compiled_artifact": "build/dr31_x509_cms.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "Private key (DEFECTIVE: CEK unwrap derives key without private key)",
            "public_inputs": "X.509 certificate and CMS EnvelopedData payloads",
            "final_outputs": "Signature validation status and unwrapped CEK",
            "normative_source": "RFC 5280 / RFC 5652 / RFC 8414",
            "vector_set": "Repository test cases (25 cases)",
            "independent_oracle": "DR31 internal host reference (reproduces parity check and secret-free CEK)",
            "host_involvement": "Buffer transport, comparison",
            "device_resident_computation": "DEFECTIVE: 1-bit parity signature check; secret-free CEK unwrap via constant XOR",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "QUARANTINED (Parity Check & Secret-Free CEK)",
            "physical_provenance_status": "QUARANTINED",
            "known_semantic_security_status": "CRITICAL_SEMANTIC_DEFECT",
            "blocker": "DR31-PARITY-CHECK-AND-PUBLIC-CEK (Signature verify is 1-bit parity; CEK unwrap lacks private key)",
            "final_classification": "BLOCKED_THREE_STRIKES"
        },
        {
            "dr_id": "DR32",
            "claimed_operation": "Post-Quantum X.509 PKI & TLS 1.3 Formatter Audit & Host Utility",
            "customer_demo_relevance": "HOST_ONLY",
            "dependencies": [],
            "source_files": ["phoenix_sdr_dsp/pqc/dr32_pki_tls_formatter.py"],
            "graph_and_abi": {"graph": None, "abi": None},
            "compiled_artifact": None,
            "tile_assignment_and_topology": None,
            "secret_inputs": "None (host utility)",
            "public_inputs": "X.509 ASN.1 DER buffers and TLS 1.3 ClientHello/ServerHello bytes",
            "final_outputs": "Formatted and validated protocol records",
            "normative_source": "RFC 5280 / RFC 8446 (TLS 1.3)",
            "vector_set": "Standard X.509 and TLS test corpus",
            "independent_oracle": "Host Python cryptography / OpenSSL asn1parse",
            "host_involvement": "100% Host CPU parsing and formatting utility",
            "device_resident_computation": "NONE (Explicitly labeled [HOST FORMATTER])",
            "potential_fallback_paths": "N/A (Host-only utility)",
            "expected_test_count": 10,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "PASS [HOST FORMATTER]",
            "physical_provenance_status": "NONE",
            "known_semantic_security_status": "HOST_ONLY",
            "blocker": None,
            "final_classification": "HOST_VERIFIED_ONLY"
        },
        {
            "dr_id": "DR33",
            "claimed_operation": "Physical Side-Channel Power/EM Trace Acquisition & TVLA Framework",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR0", "DR9"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr33_side_channel_tvla.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr33_side_channel_tvla_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr33_side_channel_tvla_abi.py"
            },
            "compiled_artifact": "build/dr33_side_channel_tvla.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "Fixed vs random test vectors",
            "public_inputs": "Acquisition parameters",
            "final_outputs": "T-statistic trace points and leakage metrics (25 cases)",
            "normative_source": "ISO/IEC 17825 (Testing methods for side-channel security)",
            "vector_set": "TVLA fixed vs random evaluation set",
            "independent_oracle": "Host Welch t-test statistical oracle",
            "host_involvement": "Trace transport, buffer dispatch, comparison",
            "device_resident_computation": "Hardware target execution triggering and on-tile accumulator profiling",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "CANONICAL-RUNNER-UNREGISTERED",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR34",
            "claimed_operation": "Hardware Root of Trust, TCG DICE / TPM Attestation & Enclave Security Boundaries",
            "customer_demo_relevance": "QUARANTINED",
            "dependencies": ["DR10"],
            "source_files": [
                "phoenix_sdr_dsp/pqc/kernels/dr34_dice_tpm.cc",
                "phoenix_sdr_dsp/pqc/kernels/dr34_dice_tpm_service.cc"
            ],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr34_dice_tpm_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr34_dice_tpm_abi.py"
            },
            "compiled_artifact": "build/dr34_dice_tpm.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "Device Identity Compound Engine (DICE) CDI secrets",
            "public_inputs": "TPM quote requests, PCR selection",
            "final_outputs": "Attestation quotes and verification status",
            "normative_source": "TCG DICE Architecture / TPM 2.0 Library Specification",
            "vector_set": "Repository test cases (25 cases)",
            "independent_oracle": "DR34 internal host oracle",
            "host_involvement": "Buffer marshaling, dispatch, comparison",
            "device_resident_computation": "DEFECTIVE: Quote signature verification checks only sig_bytes[0] != 0xFF (sentinel byte check)",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "QUARANTINED (Sentinel Byte Signature Check)",
            "physical_provenance_status": "QUARANTINED",
            "known_semantic_security_status": "CRITICAL_SEMANTIC_DEFECT",
            "blocker": "DR34-SENTINEL-BYTE-CHECK (Quote verify accepts any signature byte != 0xFF)",
            "final_classification": "BLOCKED_THREE_STRIKES"
        },
        {
            "dr_id": "DR35",
            "claimed_operation": "Truthful Physical Power, Energy & Hardware Telemetry Harvester",
            "customer_demo_relevance": "HOST_ONLY",
            "dependencies": [],
            "source_files": ["phoenix_sdr_dsp/pqc/dr35_telemetry_harvester.py"],
            "graph_and_abi": {"graph": None, "abi": None},
            "compiled_artifact": None,
            "tile_assignment_and_topology": None,
            "secret_inputs": "None",
            "public_inputs": "System sensor readings",
            "final_outputs": "Telemetry snapshots and energy metrics",
            "normative_source": "Windows Management Instrumentation (WMI) / AMD Energy Driver Specifications",
            "vector_set": "System sensor test points",
            "independent_oracle": "Host WMI/OS telemetry oracle",
            "host_involvement": "100% Host CPU telemetry harvesting and logging utility",
            "device_resident_computation": "NONE (Explicitly labeled [HOST RUNTIME])",
            "potential_fallback_paths": "N/A (Host-only utility)",
            "expected_test_count": 5,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "PASS [HOST RUNTIME]",
            "physical_provenance_status": "NONE",
            "known_semantic_security_status": "HOST_ONLY",
            "blocker": None,
            "final_classification": "HOST_VERIFIED_ONLY"
        },
        {
            "dr_id": "DR36",
            "claimed_operation": "Formal Verification & SMT Proof Models for AIE2 Cryptographic Pipelines",
            "customer_demo_relevance": "HOST_ONLY",
            "dependencies": [],
            "source_files": ["phoenix_sdr_dsp/pqc/dr36_formal_verification.py"],
            "graph_and_abi": {"graph": None, "abi": None},
            "compiled_artifact": None,
            "tile_assignment_and_topology": None,
            "secret_inputs": "None",
            "public_inputs": "Symbolic model constraints",
            "final_outputs": "SMT solver outputs and verification reports",
            "normative_source": "SMT-LIB 2.0 / Z3 Theorem Prover Standards",
            "vector_set": "Algebraic constraint test models",
            "independent_oracle": "Z3 Python SMT solver",
            "host_involvement": "100% Host CPU formal property checker",
            "device_resident_computation": "NONE (Host formal verification script; strided python loop was mislabeled as 100% formal proof)",
            "potential_fallback_paths": "N/A (Host-only analysis tool)",
            "expected_test_count": 8,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "QUARANTINED (Strided Sampling Mislabeled as SMT Proof)",
            "physical_provenance_status": "NONE",
            "known_semantic_security_status": "CRITICAL_SEMANTIC_DEFECT",
            "blocker": "DR36-STRIDED-FORMAL-DEFECT (Strided integer sampling claimed as universal formal proof)",
            "final_classification": "BLOCKED_THREE_STRIKES"
        },
        {
            "dr_id": "DR37",
            "claimed_operation": "Dual-Scheme Hybrid Classical / Quantum-Safe KEM Engine (X25519 + ML-KEM)",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR7", "DR18"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr37_hybrid_kem.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr37_hybrid_kem_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr37_hybrid_kem_abi.py"
            },
            "compiled_artifact": "build/dr37_hybrid_kem.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "X25519 scalar and ML-KEM private key",
            "public_inputs": "X25519 peer public key and ML-KEM ciphertext",
            "final_outputs": "Hybrid shared secret (25 cases)",
            "normative_source": "IETF draft-ietf-tls-hybrid-design / NIST SP 800-56C",
            "vector_set": "Repository hybrid KEM test vectors",
            "independent_oracle": "Host hybrid reference oracle",
            "host_involvement": "Input marshaling, buffer dispatch, comparison",
            "device_resident_computation": "Curve25519 scalar mult, ML-KEM decapsulation, and key combination on tile",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "CANONICAL-RUNNER-UNREGISTERED",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR38",
            "claimed_operation": "NIST SP 800-22 Randomness Statistical Battery & BSI AIS 31 Hardware Diagnostic",
            "customer_demo_relevance": "QUARANTINED",
            "dependencies": ["DR27"],
            "source_files": [
                "phoenix_sdr_dsp/pqc/kernels/dr38_randomness.cc",
                "phoenix_sdr_dsp/pqc/dr38_randomness_abi.py"
            ],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr38_randomness_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr38_randomness_abi.py"
            },
            "compiled_artifact": "build/dr38_randomness.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "Entropy sample stream",
            "public_inputs": "Test threshold parameters",
            "final_outputs": "Statistical test results and pass/fail booleans",
            "normative_source": "NIST SP 800-22 Rev 1a / BSI AIS 31",
            "vector_set": "Repository randomness test vectors (25 cases)",
            "independent_oracle": "DR38 internal host oracle",
            "host_involvement": "Sample marshaling, buffer dispatch, comparison",
            "device_resident_computation": "DEFECTIVE: Predicate max_byte_freq <= sample_len/64 is claimed to guarantee >= 7.95 bits/byte, but 64 equally frequent symbols have H = 6.0 bits/byte",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "QUARANTINED (Mathematically Invalid Entropy Threshold)",
            "physical_provenance_status": "QUARANTINED",
            "known_semantic_security_status": "CRITICAL_SEMANTIC_DEFECT",
            "blocker": "DR38-ENTROPY-PREDICATE (Flawed Shannon entropy threshold allows low-entropy inputs to pass)",
            "final_classification": "BLOCKED_THREE_STRIKES"
        },
        {
            "dr_id": "DR39",
            "claimed_operation": "dudect Side-Channel Timing & TVLA Diagnostic Engine",
            "customer_demo_relevance": "QUARANTINED",
            "dependencies": ["DR0", "DR9"],
            "source_files": [
                "phoenix_sdr_dsp/pqc/kernels/dr39_dudect.cc",
                "phoenix_sdr_dsp/pqc/kernels/dr39_dudect_service.cc"
            ],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr39_dudect_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr39_dudect_abi.py"
            },
            "compiled_artifact": "build/dr39_dudect.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "Class 0 vs Class 1 test inputs",
            "public_inputs": "Sample count descriptor",
            "final_outputs": "Welford t-statistic accumulator values",
            "normative_source": "dudect timing leakage detection methodology",
            "vector_set": "Repository test cases (25 cases)",
            "independent_oracle": "DR39 internal host oracle",
            "host_involvement": "Sample marshaling, buffer dispatch, comparison",
            "device_resident_computation": "DEFECTIVE: Feeds hardcoded constants 48/48 into Welford accumulators; does not measure physical AIE2 hardware timer cycles",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "QUARANTINED (Hardcoded Constants in Timing Accumulators)",
            "physical_provenance_status": "QUARANTINED",
            "known_semantic_security_status": "CRITICAL_SEMANTIC_DEFECT",
            "blocker": "DR39-HARDCODED-TIMING (Accumulators receive fixed constants instead of actual cycle measurements)",
            "final_classification": "BLOCKED_THREE_STRIKES"
        },
        {
            "dr_id": "DR40",
            "claimed_operation": "Reproducible High-Throughput Hardware Benchmark Protocol & Profiling Battery",
            "customer_demo_relevance": "EXTENSION_PROTOCOL",
            "dependencies": ["DR2d", "DR7", "DR12", "DR13"],
            "source_files": ["phoenix_sdr_dsp/pqc/kernels/dr40_benchmark.cc"],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr40_benchmark_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr40_benchmark_abi.py"
            },
            "compiled_artifact": "build/dr40_benchmark.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "Benchmarking keys and payloads",
            "public_inputs": "Iteration count",
            "final_outputs": "Throughput and latency profiling records (25 cases)",
            "normative_source": "Repository Hardware Benchmark Protocol",
            "vector_set": "Repository benchmark vectors",
            "independent_oracle": "Host benchmark analysis oracle",
            "host_involvement": "Dispatch timing, comparison",
            "device_resident_computation": "High-frequency pipelined dispatch execution on tile array",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "25/25 BIT_EXACT_MATCHING",
            "physical_provenance_status": "SELF_REPORTED_UNVERIFIED",
            "known_semantic_security_status": "VALID_ALGORITHMIC_IMPLEMENTATION",
            "blocker": "CANONICAL-RUNNER-UNREGISTERED",
            "final_classification": "HISTORICAL_UNVERIFIED"
        },
        {
            "dr_id": "DR41",
            "claimed_operation": "Quantum Key Management System (Q-KMS) Integration & Hybrid Key Lifecycle Engine",
            "customer_demo_relevance": "QUARANTINED",
            "dependencies": ["DR10", "DR16", "DR18"],
            "source_files": [
                "phoenix_sdr_dsp/pqc/kernels/dr41_qkms.cc",
                "phoenix_sdr_dsp/pqc/kernels/dr41_qkms_service.cc"
            ],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr41_qkms_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr41_qkms_abi.py"
            },
            "compiled_artifact": "build/dr41_qkms.xclbin",
            "tile_assignment_and_topology": "AIE2 Tile (0,2)",
            "secret_inputs": "DEFECTIVE: Host provides entire vault on each dispatch",
            "public_inputs": "Key policy requests",
            "final_outputs": "Derived keys and status records",
            "normative_source": "ETSI GS QKD 014 / NIST SP 800-130",
            "vector_set": "Repository test cases (25 cases)",
            "independent_oracle": "DR41 internal host oracle",
            "host_involvement": "Host stores and provides complete vault memory on each call",
            "device_resident_computation": "DEFECTIVE: Ephemeral vault reconstructed on host; no persistent, tamper-resistant on-tile vault exists across dispatches",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 25,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "QUARANTINED (Ephemeral Host-Supplied Vault)",
            "physical_provenance_status": "QUARANTINED",
            "known_semantic_security_status": "CRITICAL_SEMANTIC_DEFECT",
            "blocker": "DR41-EPHEMERAL-VAULT (No persistent on-tile hardware key lifecycle protection)",
            "final_classification": "BLOCKED_THREE_STRIKES"
        },
        {
            "dr_id": "DR42",
            "claimed_operation": "ANSSI Composite & Dual-Signature Sovereign Standard Engine",
            "customer_demo_relevance": "QUARANTINED",
            "dependencies": ["DR13"],
            "source_files": [
                "phoenix_sdr_dsp/pqc/kernels/dr42_composite_sig.cc",
                "phoenix_sdr_dsp/pqc/kernels/dr42_composite_sig_internal.hpp"
            ],
            "graph_and_abi": {
                "graph": "phoenix_sdr_dsp/pqc/dr42_composite_sig_graph.py",
                "abi": "phoenix_sdr_dsp/pqc/dr42_composite_sig_abi.py"
            },
            "compiled_artifact": "build/dr42_composite_sig.xclbin",
            "tile_assignment_and_topology": "AIE2 Tiles (0,2)-(0,3)",
            "secret_inputs": "Dual private keys",
            "public_inputs": "Dual public keys, message, composite signature",
            "final_outputs": "Verification boolean (35 cases)",
            "normative_source": "ANSSI Composite Signature Specification / Draft IETF Composite Signatures",
            "vector_set": "Repository test cases (35 cases)",
            "independent_oracle": "DR42 internal host oracle (reproduces parity shortcut)",
            "host_involvement": "Buffer marshaling, dispatch, comparison",
            "device_resident_computation": "DEFECTIVE: verify_classical_signature and verify_pqc_signature perform (check & 0x01) == 0 low-bit parity check instead of actual signature verification; test fixtures fudge bit 0",
            "potential_fallback_paths": "NONE (Fail-closed on NPU error)",
            "expected_test_count": 35,
            "registered_canonical_test_count": 0,
            "latest_observed_functional_result": "QUARANTINED (1-Bit Parity Signature Check)",
            "physical_provenance_status": "QUARANTINED",
            "known_semantic_security_status": "CRITICAL_SEMANTIC_DEFECT",
            "blocker": "DR42-PARITY-SIGNATURE-CHECK (Verification is a trivial 1-bit parity predicate)",
            "final_classification": "BLOCKED_THREE_STRIKES"
        }
    ]

    manifest = {
        "schema_version": "1.0.0",
        "generated_at": "2026-09-05T23:30:00Z",
        "repository": "phoenix-npu-pqc",
        "git_branch": "audit/customer-critical-readiness",
        "roadmap_scope": "DR0 through DR42 inclusive",
        "excluded_scope": ["DR43"],
        "overall_customer_acceptance_verdict": "NO-GO",
        "verdict_rationale": (
            "The full DR0-DR42 roadmap contains multiple critical semantic security defects (DR21, DR22, "
            "DR30, DR31, DR34, DR36, DR38, DR39, DR41, DR42) where trivial parity checks, sentinel byte "
            "predicates, host-supplied shared secrets, secret-free signing, or fixed accumulators were "
            "substituted for genuine cryptographic operations. Under the mandatory zero-speculation and "
            "kernel-integrity policy, these deliverables are strictly quarantined. Customer acceptance "
            "for the un-quarantined full roadmap is strictly NO-GO. A customer demonstration must be "
            "strictly bounded to authentic, verified on-tile core primitives (ML-KEM, ML-DSA, Keccak/SHAKE)."
        ),
        "accounting_breakdown": {
            "total_roadmap_milestones": len(drs),
            "canonical_core_gates": 19,
            "canonical_core_cases": 736,
            "canonical_extension_gates": 5,
            "canonical_extension_cases": 121,
            "canonical_all_gates": 24,
            "canonical_all_cases": 857,
            "standalone_scripts": 18,
            "standalone_cases": 460,
            "total_repository_scripts": 42,
            "total_nominal_cases": 1317,
            "quarantined_milestones_count": 10,
            "blocked_milestones_count": 1,
            "host_only_milestones_count": 2,
            "authentic_candidate_milestones_count": 30
        },
        "milestones": drs
    }
    return manifest


def main():
    manifest = generate_scope_matrix()
    out_file = CUSTOMER_DEMO_DIR / "CUSTOMER_SCOPE.json"
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
    print(f"Authoritative scope matrix written to {out_file} ({len(manifest['milestones'])} milestones)")


if __name__ == "__main__":
    main()
